<?php
/**
 * Gift Voucher View Product template
 */
?>
<?php
$_product = $this->getProduct();
$_giftAmount = $this->getGiftAmount($_product);
$_formData = $this->getFormConfigData();
// echo $this->getPriceHtml($_product); //Hai.Tran
?>

<div id="giftcard-product-amount-media" style="display: none"></div> 
<input type="hidden" name="price_amount" id="price_amount" value="0" />
<script type="text/javascript">
    var giftmedia = new Array('giftcard-template-back', 'giftcard-template-top', 'giftcard-template-left');
    var giftAmountChange = <?php echo Mage::helper('core')->jsonEncode($_giftAmount) ?>; //Hai.Tran
    giftCardPriceFomat = <?php echo $this->getPriceFormatJs() ?>;
    function changePriceMediaGiftcard(value) {
        for (i = 0; i < 3; i++)
            if ($(giftmedia[i]))
                $(giftmedia[i]).down('.giftcard-price-change').innerHTML = value;
    }
</script>
<script type="text/javascript">
//<![CDATA[
    Event.observe(window, 'load', function() {
		if ($$('.product-shop')[0].down('.price-info'))
			$$('.product-shop')[0].down('.price-info').setStyle({'display':'none'});
        changePriceMediaGiftcard($('giftcard-product-amount-media').innerHTML);
        changeSenderName($('customer_name'));
        changeReceiverName($('recipient_name'));
        changeRemaining($('message'));
    });
//]]>
</script>

<div class="price-box">
    <span class="regular-price">
        <span class="price" id="giftcard-product-price">
        </span>
    </span>
</div>
<h3 style="font-size: 16px;" class="txtBlack txtBebas">ZIPPO EGIFT CARDS, always the perfect gift! </h3>

<dl class="gcPurchase">
<dt class="txtBebas gcPurchStepHdr"><span class="txtBlack">1.</span> <span class="txtRed">CHOOSE A CARD</span> </dt>
                                    <dd class="gcStep1">
                                        <ul class="gcImages">
                                        
                                            <li class="gcChoice clearfix">
                                                <div class="radio" id="uniform-undefined"><span class="checked"><input type="radio" checked="checked" class="radDef" value="1" name="gcImage" style="opacity: 0;"></span></div>
                                                <label class="lblImage">
                                                    <img width="221" height="139" alt="Zippo eGift Card" src="http://images.zippo.com/images/products/1_1025143_TH_1.jpg"></label>
                                            </li>
                                            
                                            <li class="gcChoice clearfix">
                                                <div class="radio" id="uniform-undefined"><span><input type="radio" class="radDef" value="10" name="gcImage" style="opacity: 0;"></span></div>
                                                <label class="lblImage">
                                                    <img width="221" height="139" alt="Zippo eGift Card" src="http://images.zippo.com/images/products/1_1025143_TH_10.jpg"></label>
                                            </li>
                                            
                                            <li class="gcChoice clearfix">
                                                <div class="radio" id="uniform-undefined"><span><input type="radio" class="radDef" value="2" name="gcImage" style="opacity: 0;"></span></div>
                                                <label class="lblImage">
                                                    <img width="221" height="139" alt="Zippo eGift Card" src="http://images.zippo.com/images/products/1_1025143_TH_2.jpg"></label>
                                            </li>
                                            
                                            <li class="gcChoice clearfix">
                                                <div class="radio" id="uniform-undefined"><span><input type="radio" class="radDef" value="3" name="gcImage" style="opacity: 0;"></span></div>
                                                <label class="lblImage">
                                                    <img width="221" height="139" alt="Zippo eGift Card" src="http://images.zippo.com/images/products/1_1025143_TH_3.jpg"></label>
                                            </li>
                                            
                                            <li class="gcChoice clearfix">
                                                <div class="radio" id="uniform-undefined"><span><input type="radio" class="radDef" value="4" name="gcImage" style="opacity: 0;"></span></div>
                                                <label class="lblImage">
                                                    <img width="221" height="139" alt="Zippo eGift Card" src="http://images.zippo.com/images/products/1_1025143_TH_4.jpg"></label>
                                            </li>
                                            
                                            <li class="gcChoice clearfix">
                                                <div class="radio" id="uniform-undefined"><span><input type="radio" class="radDef" value="5" name="gcImage" style="opacity: 0;"></span></div>
                                                <label class="lblImage">
                                                    <img width="221" height="139" alt="Zippo eGift Card" src="http://images.zippo.com/images/products/1_1025143_TH_5.jpg"></label>
                                            </li>
                                            
                                            <li class="gcChoice clearfix">
                                                <div class="radio" id="uniform-undefined"><span><input type="radio" class="radDef" value="6" name="gcImage" style="opacity: 0;"></span></div>
                                                <label class="lblImage">
                                                    <img width="221" height="139" alt="Zippo eGift Card" src="http://images.zippo.com/images/products/1_1025143_TH_6.jpg"></label>
                                            </li>
                                            
                                            <li class="gcChoice clearfix">
                                                <div class="radio" id="uniform-undefined"><span><input type="radio" class="radDef" value="7" name="gcImage" style="opacity: 0;"></span></div>
                                                <label class="lblImage">
                                                    <img width="221" height="139" alt="Zippo eGift Card" src="http://images.zippo.com/images/products/1_1025143_TH_7.jpg"></label>
                                            </li>
                                            
                                            <li class="gcChoice clearfix">
                                                <div class="radio" id="uniform-undefined"><span><input type="radio" class="radDef" value="8" name="gcImage" style="opacity: 0;"></span></div>
                                                <label class="lblImage">
                                                    <img width="221" height="139" alt="Zippo eGift Card" src="http://images.zippo.com/images/products/1_1025143_TH_8.jpg"></label>
                                            </li>
                                            
                                            <li class="gcChoice clearfix">
                                                <div class="radio" id="uniform-undefined"><span><input type="radio" class="radDef" value="9" name="gcImage" style="opacity: 0;"></span></div>
                                                <label class="lblImage">
                                                    <img width="221" height="139" alt="Zippo eGift Card" src="http://images.zippo.com/images/products/1_1025143_TH_9.jpg"></label>
                                            </li>
                                            
                                        </ul>
                                    </dd>
                                    <dt class="txtBebas gcPurchStepHdr clear"><span class="txtBlack">2.</span> <span class="txtRed">CHOOSE Amount</span> </dt>
                                    <dd id="gcStep2" class="gcStep2 txtA7 clearfix">
                                        <div style="border-right: 1px solid #e9e9e9; float: left; line-height: 32px; margin-right: 18px; width: 123px;">
                                            <?php if ($_giftAmount['type'] == 'range'): ?>
        <p>
            <?php
            $includeTax = ( Mage::getStoreConfig('tax/display/type') != 1 );
            $rateTax = Mage::helper('tax')->getPrice($_product, 100, $includeTax) / 100;
            ?>
            <label for="amount_range"><div style="float: left; width:100px"><?php echo $this->__('Enter value:') ?></div></label>
            <input id="amount_range" name="amount" class="input-text required-entry validate-greater-than-zero" onchange="validateInputRange(this);" value="<?php echo $_formData->getAmount() ?>" />
            (<span class="price"><?php echo $_giftAmount['from_txt'] ?></span> -  <span class="price"><?php echo $_giftAmount['to_txt'] ?></span>)
            <script type="text/javascript">
                //<![CDATA[
                var rateTax = <?php echo $rateTax ?>;
                if (!$('amount_range').value)
                    $('amount_range').value = <?php echo $_giftAmount['from'] ?>;
                function validateInputRange(el) {
                    var gift_amount_min = <?php echo $_giftAmount['from'] ?>;
                    var gift_amount_max = <?php echo $_giftAmount['to'] ?>;
                    if (el.value < gift_amount_min)
                        el.value = gift_amount_min;
                    if (el.value > gift_amount_max)
                        el.value = gift_amount_max;

                    changePriceByInput(el.value);
                }
                changePriceByInput($('amount_range').value);
                function changePriceByInput(value) {
                    if (giftAmountChange.gift_price_type == 'percent') {
                        $('giftcard-product-price').innerHTML = formatCurrency(value * giftAmountChange.gift_price_options / 100 * rateTax, giftCardPriceFomat);
                        $('price_amount').value = value * giftAmountChange.gift_price_options / 100 * rateTax;
                    } else {
                        $('giftcard-product-price').innerHTML = formatCurrency(value * rateTax, giftCardPriceFomat);
                        $('price_amount').value = value * rateTax;
                    }
                    $('giftcard-product-amount-media').innerHTML = formatCurrency(value, giftCardPriceFomat);
                    changePriceMediaGiftcard($('giftcard-product-amount-media').innerHTML);
                }
                //]]>
            </script>
        </p>
    <?php elseif ($_giftAmount['type'] == 'dropdown'): ?>
       
            
            <select id="amount_dropdown" name="amount" class="required-entry select" onchange="changePriceByInputDropdown(this)">
                <?php $options = array_combine($_giftAmount['options'], $_giftAmount['options_txt']) ?>
                <?php foreach ($options as $value => $label): ?>
                    <option value="<?php echo $value ?>" <?php if ($value == $_formData->getAmount()) echo 'selected' ?> ><?php echo $label ?></option>
                <?php endforeach ?>
            </select>
            <script type="text/javascript">
                //<![CDATA[
                function changePriceByInputDropdown(el) {
                    $('giftcard-product-price').innerHTML = formatCurrency(giftAmountChange.prices[el.value], giftCardPriceFomat);
                    $('price_amount').value = giftAmountChange.prices[el.value];
                    $('giftcard-product-amount-media').innerHTML = el.options[el.selectedIndex].text;
                    changePriceMediaGiftcard($('giftcard-product-amount-media').innerHTML);
                }
                changePriceByInputDropdown($('amount_dropdown'));
                //]]>
            </script>
       
    <?php elseif ($_giftAmount['type'] == 'static'): ?>
        
            <?php echo $this->__('Gift Card value: <span class="regular-price">%s</span>', $_giftAmount['value_txt']) ?>
            <input type="hidden" name="amount" value="<?php echo $_giftAmount['value'] ?>" />
            <script type="text/javascript">
                //<![CDATA[
                $('price_amount').value = giftAmountChange.price;
                $('giftcard-product-price').innerHTML = formatCurrency(giftAmountChange.price, giftCardPriceFomat);
                $('giftcard-product-amount-media').innerHTML = '<?php echo $_giftAmount['value_txt'] ?>';
                //]]>
            </script>
       
    <?php endif ?>
                                            </div>
                                        <!--<div style="float: left; line-height: 32px; width: 150px;">
                                            <label style="float: left; margin: 0 8px 0 0;" for="txtGCQty" class="txtBebas">QTY</label>
                                            <input type="text" class="txtDef txt3" name="txtGCQty" id="txtGCQty" />
                                        </div>-->
                                    </dd>
                                    <dt class="txtBebas gcPurchStepHdr"><span class="txtBlack">3.</span> <span class="txtRed">CHOOSE A Recipient</span> </dt>
                                    <dd class="gcStep3 txtBebas txtBlack clearfix">
                                        <p id="pErrorMsg" style="display: none; margin: 12px 0;" class="txtRed">Please complete all fields marked '*'</p>
                                       
                                       <div class="giftvoucher-product-info">
    
    <?php echo $this->getChildHtml('giftcard.product.selecttemplate') ?>
        
    <div class="giftvoucher-receiver" id="giftvoucher-receiver" style="<?php if (!$_formData->getSendFriend()) echo 'display:none;' ?>">
    
    <ul class="gcForm">
    	<li>

            <label for="customer_name"><?php echo $this->__('TO') ?></label><br />
            <input type="text" class="txtDef" name="customer_name" id="customer_name" value="<?php echo $_formData->getCustomerName() ?>" onchange="changeSenderName(this);" maxlength="30"/>
    
        </li>

        <li>
        <label for="recipient_name"><?php echo $this->__('FROM') ?></label><br />
            <input type="text" class="txtDef required-entry" name="recipient_name" id="recipient_name" value="<?php echo $_formData->getRecipientName() ?>"  onchange="changeReceiverName(this);" maxlength="30"/>
        </li>
        <li class="clear">
         <label class = "recipient_email" for="recipient_email"><?php echo $this->__('RECIPIENT EMAIL') ?></label><br />
            <input type="text" class="txtDef required-entry validate-email validate-same-email" name="recipient_email" id="recipient_email" value="<?php echo $_formData->getRecipientEmail() ?>" />
        
        </li>
        <li class="">
         <label class = "recipient_email" for="recipient_email"><?php echo $this->__('CONFIRM RECIPIENTS EMAIL') ?></label><br />
            <input type="text" class="txtDef required-entry validate-email validate-same-email" name="recipient_email" id="recipient_email" value="<?php echo $_formData->getRecipientEmail() ?>" />
        
        </li>
        
        <li class="clear width100">

        <?php //if ($this->enableCustomMessage()):   ?>
            <label class = "message" for="message"><?php echo $this->__('Gift Message') ?></label><br />
            <textarea maxlength="<?php echo $this->messageMaxLen(); ?>" name="message" id="message" class="bigTxtArea" onchange="changeRemaining(this);" onkeyup="changeRemaining(this);"><?php echo $_formData->getMessage() ?></textarea><br />
            <small><?php echo $this->__('Characters Remaining: ') ?><span id="giftvoucher_char_remaining"><?php echo $this->messageMaxLen() ?></span></small>
            <script type="text/javascript">
                //<![CDATA[
                var remaining_max = <?php echo $this->messageMaxLen() ?>;
                function changeRemaining(el) {
                    if (el.value.length > remaining_max) {
                        el.value = el.value.substring(0, remaining_max);
                    }
                    $('giftvoucher_char_remaining').innerHTML = remaining_max - el.value.length;
                    for (i = 0; i < 3; i++)
                        if ($(giftmedia[i]))
                            $(giftmedia[i]).down('.giftcard-custom-message').innerHTML = el.value;
                }
                function changeSenderName(el) {
                    for (i = 0; i < 3; i++)
                        if ($(giftmedia[i]))
                            if(el.value) $(giftmedia[i]).down('.giftcard-send-from').innerHTML = el.value;
                            else $(giftmedia[i]).down('.giftcard-send-from').innerHTML = '<?php echo Mage::helper('customer')->isLoggedIn() ? Mage::helper('customer')->getCustomerName() : ''; ?>';
                }
                function changeReceiverName(el) {
                    for (i = 0; i < 3; i++)
                        if ($(giftmedia[i]))
                            $(giftmedia[i]).down('.giftcard-send-to').innerHTML = el.value;
                }

                same_email = '<?php echo $this->__('You can not send giftcard for yourselve.') ?>';
                Validation.add('validate-same-email', same_email, function(v) {
                    if (Validation.get('validate-email').test(v)) {
                        if (v === '<?php echo Mage::getSingleton('customer/session')->getCustomer()->getEmail() ?>')
                            return false;
                    }
                    return true;
                });
                //]]>
            </script>
        <?php //endif  ?>
        </li>
       <li class="clearfix">
       
       
       
       <?php if ($this->enableScheduleSend()): ?>
    <?php echo $this->getLayout()->createBlock('core/html_calendar')->setTemplate('page/js/calendar.phtml')->toHtml() ?>
        <p class = "giftcard-date-box"style="width: 200px; float: left">
                <label for="day_to_send"><?php echo $this->__('Day to send') ?></label><br />
                <img src="<?php echo Mage::getBaseUrl('skin') ?>/adminhtml/default/default/images/grid-cal.gif" alt="<?php echo $this->__('Select Date') ?>" class="v-middle" id="calendar-day_to_send" />
                <input type="text" class="input-text required-entry validate-date validate-date-giftcard" name="day_to_send" id="day_to_send" value="<?php echo $_formData->getDayToSend() ?>" style="float: left; margin-right: 3px"/>
            </p>
            <script type="text/javascript">
                //<![CDATA[
                Calendar.setup({
                    inputField: "day_to_send",
                    ifFormat: "%m/%e/%Y",
                    showsTime: false,
                    button: "calendar-day_to_send",
                    align: "Bl",
                    singleClick: true,
                    disableFunc: function(date) {
                        var today_date = new Date();
                        today_date.setHours(0);
                        today_date.setMinutes(0);
                        today_date.setSeconds(0);
                        today_date.setMilliseconds(0);
                        if (date < today_date)
                            return true;
                        return false;
                    }
                });
                //Hai.Tran
                day_to_send_error = '<?php echo $this->__('We cannot send this giftcard in the past.') ?>';
                Validation.add('validate-date-giftcard', day_to_send_error, function(v) {
                    if (Validation.get('validate-date').test(v)) {
                        var test = new Date(v);
                        var today = getTodayDate();
                        if (test < today)
                            return false;
                    }
                    return true;
                });
                function getTodayDate() {
                    todayDate = new Date();
                    todayDate.setHours(0);
                    todayDate.setMinutes(0);
                    todayDate.setSeconds(0);
                    todayDate.setMilliseconds(0);
                    return todayDate;
                }
                //]]>
            </script>
            <style>
                #giftcard-preview-button-add{
                    margin-top: 18px;
                }
            </style>
<?php endif ?>
    <?php
    $templates = Mage::getBlockSingleton('giftvoucher/product_view')->getAvailableTemplate();
    if(count($templates)):
    ?>
    <button type="button" title="Preview template" id="giftcard-preview-button-add" style="background: #df101d; float: left; font-size: 14px; padding: 2px 4px 3px; border:none;" class="txtBebas txtWhite" onclick="getPreview()" style="float: right"><span style="background-image: url(<?php echo $this->getSkinUrl() . 'images/giftvoucher/preview-icon.png' ?>); background-repeat: no-repeat;background-size: contain; padding-left: 20px;"><span><?php echo $this->__('Preview Gift Card') ?></span></span></button>
    <?php endif; ?>
       
       
       
       
       
       
       
       
       
                                                <div class="frmBtns"><a title="clear form" style="background: #000; float: left; font-size: 14px; margin: 8px 12px 0 4px; padding: 2px 4px 3px;" class="clear txtBebas txtWhite" href="#">Clear</a> <a title="add to cart" style="background: #000; float: left; font-size: 14px; margin: 8px 0 0; padding: 2px 4px 3px;" class="txtBebas txtWhite" id="btnAddCart" href="#">Add to Cart</a> </div>
                                            
                                            
                                            
                                            
                                            
                                            
                                            
                                            
                                            </li>
    
    </ul>
    
        <div style="display:none;">
       
            <?php

            if (Mage::app()->getRequest()->getControllerName() == 'cart') {
                if ($_formData->getNotifySuccess())
                    $checkboxNotify = true;
                else
                    $checkboxNotify = false;
            } else
                $checkboxNotify = true;
            ?>
            <input type="checkbox" value="1" name="notify_success" id="notify_success" <?php if ($checkboxNotify) echo 'checked' ?> />
            
            <label for="notify_success"><?php echo $this->__('Get notification email when your friend receives Gift Card') ?></label>
        
        </div>

    <div style="clear: both"></div>
    </div>
    <p></p>
</div>
                                       
                                        
                                    </dd>
                                </dl>





