<section class="row zOutdoor" >
  <section class="listHolder listHolderWhiteBg clearfix">
    <div class="listTop listGifts clearfix">
                    	<div class="listHero listGiftsHero">
                        	<h3 class="listCatHead accessHead txtWhite txtBebas">
                            	ACCESSORIES
                            </h3>
                            <h5 class="listSubHead txtRed txtBebas">
                            	from carriers to displays, we can still get your fire burning.
                            </h5>
                            <p class="txtWhite">
                            	Aliquet adipiscing tempor ut? Magna. Velit hac, et? Odio adipiscing cras? Cum ut egestas? Pulvinar in integer turpis porta, facilisis nec amet scelerisque pulvinar sit nascetur magnis, augue eros! Lacus amet habitasse vel nisi urna! Sed et facilisis? Nunc! Adipiscing sed dapibus eu velit in lundium risus! Turpis nisi, aenean augue porta quis elementum?
                            </p>
                        </div><!-- eo .listHero -->
                    </div>
    <!-- eo .listTop -->
    
    <!-- eo .listSlider --> 
  </section>
  <!-- eo .listHolder -->
  <section class="listKickersRight">
    <section class="listKickerAdTop">
      <div class="innerKicker"> <a href="#" title="ad name"><img src="assets/img/list_kicker1.png" alt="ad name" width="224" height="270" /></a> </div>
    </section>
    <!-- eo .listKickerAdTop -->
    <section class="bestSellKicker">
      <div class="inner clearfix">
        <h3 class="bestSellHdr txtBebas"> best sellers </h3>
        <div class="bsSlider">
          <div class="bsFaker"></div>
          <strong class="shortDesc"></strong>
          <div class="bsSlideWrap clearfix" id="bsKickSlide">
            <ul id="bestSellersList">
              <li class="bsSlideItem"><img src="assets/img/bsSlider1.jpg" alt="First rugged yet refined classic" /></li>
              <li class="bsSlideItem"><img src="assets/img/bsSlider1.jpg" alt="2nd rugged yet refined classic" /></li>
              <li class="bsSlideItem"><img src="assets/img/bsSlider1.jpg" alt="3rd rugged yet refined classic" /></li>
            </ul>
            <!--<div class="bsSlideItem onDeck prevItem"><img src="assets/img/bsSlider1.jpg" alt="product name" width="107" height="146" /></div>--> 
            <!--<div class="bsSlideItem onDeck nextItem"><img src="assets/img/bsSlider1.jpg" alt="product name" width="107" height="146" /></div>--> 
          </div>
        </div>
        <div class="sliderLinks clearfix"> <a id="btnBsProdInfo" href="ProductDetail.html" title="product info"></a> <a id="btnBsAddCart" href="#" title="add to cart"></a> </div>
      </div>
    </section>
    <!-- eo .listKickerSlide -->
    <section class="kickerPromo">
      <h3 class="txtRed txtBebas"> PROMO TITLE TEXT </h3>
      <div class="kickerPromoBtm">
        <div class="inner clearfix">
          <p> Vero eos et accusamus et iusto blanditiis praesentium voluptatum deleniti atque corrupti quos! </p>
          <a class="kickerPromoLink" href="#"><strong>Lorem Ipsum Nobis</strong></a> </div>
        <!-- eo .inner --> 
      </div>
      <!-- eo .kickerPromoBTM --> 
    </section>
    <!-- eo .kickerPromo --> 
  </section>
  <!-- eo .listKickersRight --> 
</section>
