<script>
 jQuery(document).ready(function() {
	 jQuery("#from1").show();
	jQuery("#contactOptions li.first").click(function(e) {
		jQuery(".frombox").hide();
		jQuery("#from1").show();
    });
	jQuery("#contactOptions li.two").click(function(e) {
		jQuery(".frombox").hide();
		jQuery("#from2").show();
    });
	jQuery("#contactOptions li.three").click(function(e) {
		jQuery(".frombox").hide();
		jQuery("#from3").show();
    });
	jQuery("#contactOptions li.four").click(function(e) {
		jQuery(".frombox").hide();
		jQuery("#from4").show();
    });
    
});
</script>
<style>
.frombox{
	display:none;
}

</style>

<ul id="contactOptions" class="contactOpts txtBebas">
  <li class="first"><a class="contactOpt" id="lnkOnlineOrders">Online orders</a> </li>
  <li class="two"><a class="contactOpt" id="lnkSales" >New Retailer Inquiries</a> </li>
  <li class="three"><a class="contactOpt" id="lnkMedia">Media and PR</a> </li>
  <li class="four"><a class="contactOpt" id="lnkGeneral">General Inquiries</a> </li>
</ul>
<div id="contactForms" class="contactForms">
  <div id="dvOnlineOrders" class="oneform">
  	<div id="from1" class="frombox">
    <h3 id="contactHeading" class="txtRed txtBebas">ONLINE ORDERS</h3>
    <p class="txtBold">Providing exceptional service is our priority; feedback is always welcomed. If your inquiry is time-sensitive, please call us Monday-Friday 8:00 am to 4:30 pm EST at 888.442.1932.</p>
    <p class="txtBold">Fields marked with <strong class="txtRed">*</strong> are required.</p>
    <div class="tab-1">
      <form method="post" action="" name="contact_frm" id="contact_frm1">
        <?php
		 echo Mage::getStoreConfig('trans_email/ident_general/email');
					if($_POST) {
						if($_POST['txtOrderNumber'] == '')
							$empty_order_error = true;
						if($_POST['txtFname'] == '')
							$empty_nameF_error = true;
						if($_POST['txtLname'] == '')
							$empty_nameL_error = true;							
						if($_POST['txtStreet'] == '')
							$empty_street_error = true;
						if($_POST['txtCity'] == '')
							$empty_city_error = true;
						if($_POST['state'] == '')
							$empty_state_error = true;
						if($_POST['txtZipCode'] == '')
							$empty_zipo_error = true;
						if($_POST['txtPhoneArea'] == '')
							$empty_phone_error = true;							
						if($_POST['txtPhonePrefix'] == '')
							$empty_phone1_error = true;
						if($_POST['txtPhoneSuffix'] == '')
							$empty_phone2_error = true;																					
							
						if($_POST['contact_email'] == '')
							$empty_email_error = true;

						if($_POST['contact_email'] != '') {
							$expression = '[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}';
							if (eregi($expression, $_POST['contact_email'])) {
								$valid_email = true;
							}
 
						}
						if(!$empty_order_error && !$empty_nameF_error && !$empty_nameL_error && !$empty_city_error && !$empty_state_error && !$empty_zipo_error && !$empty_phone_error && !$empty_phone_error1 && $valid_email && !$empty_phone2_error) {
							$admin_email	 = 'frenklen2004@gmail.com';
							$subject		 ='ONLINE ORDERS ';
							$headers		 = 'MIME-Version: 1.0' . "\r\n";
							$headers		.= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
							$headers		.= 'To:'.$admin_email. "\r\n";
							$headers		.= 'From:'.$_POST['contact_email']."\r\n";
							$txt_Message	 = "Order Number : ".$_POST['txtOrderNumber']." . <br>
												First Name : ".$_POST['txtFname']." . <br>
												Last Name : ".$_POST['txtLname']." . <br>
												Street Address : ".$_POST['txtStreet']." . <br>
												Street Address 2 : ".$_POST['txtStreet2']." . <br>
												City : ".$_POST['txtCity']." . <br>
												State  : ".$_POST['state']." . <br>
												Zip Code : ".$_POST['txtZipCode']." . <br>
												Phone : ".$_POST['txtPhoneArea']." . <br>
												Phone : ".$_POST['txtPhonePrefix']." . <br>
												Phone : ".$_POST['txtPhoneSuffix']." . <br>
											    Email : ".$_POST['contact_email']." . <br>
											    Message : ".$_POST['contact_content']." . <br>";
							$message = $txt_Message;
							$to = $admin_email;
							mail($to, $subject, $message, $headers);
							$mail_success = true;
						}
					}
					?>
        <?php if($mail_success) { ?>
        <p class="yellow">Your email has been sent! We will contact you shortly</p>

        <?php }?>
        <ul class="contactFields">
          <li id="liOrderNum">
            <label class="txtBlack txtBebas" for="txtOrderNumber">Order Number <strong class="txtRed">*</strong></label>
				    <p class="red" id="txtOrderNumber_1_error">Name is required</p>
            <input type="text"  class="txtDef" id="txtOrderNumber_1" name="txtOrderNumber_1" value=""  />
             </li>
          
          <li class="clearfix">
            <div class="width50">
              <label class="txtBlack txtBebas" for="txtFname">First Name <strong class="txtRed">*</strong></label>
              <p class="red" id="txtFname_1_error">Name is required</p>
              <input type="text" tabindex="2" class="txtDef" id="txtFname_1" name="txtFname_1" >
            </div>
            <div class="width50">
              <label class="txtBlack txtBebas" for="txtLname">Last Name <strong class="txtRed">*</strong></label>
				 <p class="red" id="txtLname_1_error">Name is required</p>
              <input type="text" tabindex="3" class="txtDef" id="txtLname_1" name="txtLname_1" >
            </div>
          </li>
          <li class="clearfix">
            <div class="width50">
              <label class="txtBlack txtBebas" for="txtStreet">Street Address <strong class="txtRed">*</strong></label>
			  <p class="red" id="txtStreet_1_error">Name is required</p>
              <input type="text" tabindex="4" class="txtDef" id="txtStreet_1" name="txtStreet_1" >
            </div>
            <div class="width50">
              <label class="txtBlack txtBebas" for="txtStreet2">Street Address 2</label>
              <input type="text" tabindex="5" class="txtDef" id="txtStreet2_1" name="txtStreet2_1"  >
            </div>
          </li>
          <li class="clearfix">
            <div class="width50">
              <label class="txtBlack txtBebas" for="txtCity">City <strong class="txtRed">*</strong></label>
              <p class="red" id="txtCity_1_error">Name is required</p>
              <input type="text" tabindex="6" class="txtDef" id="txtCity_1" name="txtCity_1" >
            </div>
            <div id="divSelState" class="width50">
              <label class="txtBlack txtBebas" for="selState-button">State <strong class="txtRed">*</strong></label>
              <p class="red" id="state_1_error">Name is required</p>
              <select name="state" id="state_1">
                <option value="Duabi">Duabi</option>
                <option value="Abu Dahabi">Abu Dahabi</option>
              </select>
            </div>
          </li>
          <li class="clearfix clear" id="liTxtZip">
            <label class="txtBlack txtBebas" for="txtZipCode">Zip Code<strong class="txtRed">*</strong></label>
            <p class="red" id="txtZipCode_1_error">Name is required</p>
            <input type="text" tabindex="9" class="txtDef" id="txtZipCode_1" name="txtZipCode_1" >
          </li>
          <li style="margin-top: 9px;" class="clearfix">
            <div class="width50">
              <label class="txtBlack txtBebas" for="txtPhoneArea">Phone <strong class="txtRed">*</strong></label>
              <p class="red" id="txtPhoneArea_1_error">Name is required</p>
              <p class="red" id="txtPhonePrefix_1_error">Name is required</p>
              <p class="red" id="txtPhoneSuffix_1_error">Name is required</p>

              <input type="text" class="txtDef txt3" tabindex="11" id="txtPhoneArea_1" maxlength="3" name="txtPhoneArea" >
              <input type="text" class="txtDef txt3" tabindex="12" id="txtPhonePrefix_1" maxlength="3" name="txtPhonePrefix" >
              <input type="text" class="txtDef txt4" tabindex="13" id="txtPhoneSuffix_1" maxlength="4" name="txtPhoneSuffix" >
            </div>
            <div class="width50">
              <label class="txtBlack txtBebas" for="txtEmail">Email <strong class="txtRed">*</strong></label>
              <p class="red" id="txtEmail_1_error">Name is required</p>
              <input type="text" class="txtDef" tabindex="14" id="txtEmail_1" name="contact_email" >
            </div>
          </li>
          <li class="clear">
            <label class="txtBlack txtBebas" for="txtMessage">Message</label>
             <textarea name="contact_content" id="contact_content_1" class="bigTxtArea" cols="" rows="">
</textarea>
          </li>
          <li class="clearfix">
          	<button type="button" class="lnkBlkWhtArw" style="float:right;" onclick="onlineOrder('_1');" >
            	<span>submit</span>
            </button>
            </li>
        </ul>
      </form>
    </div>
    </div>
   
   <script language="javascript">
   function onlineOrder(id){

	   var txtOrderNumber = jQuery('#txtOrderNumber'+id).val();
	   
	   if(txtOrderNumber==''){
		 jQuery('#txtOrderNumber'+id+'_error').show();
	   }else{
		   jQuery('#txtOrderNumber'+id+'_error').hide();
	   }


	   var txtFname = jQuery('#txtFname'+id).val();
	   if(txtFname==''){
		   jQuery('#txtFname'+id+'_error').show();
	   }else{
		   jQuery('#txtFname'+id+'_error').hide();
	   } 
	  
	   
	   var txtLname = jQuery('#txtLname'+id).val();
	   if(txtLname==''){
		   jQuery('#txtLname'+id+'_error').show();
	   }else{
		   jQuery('#txtLname'+id+'_error').hide();
	   }


	   var txtStreet = jQuery('#txtStreet'+id).val();
	   if(txtStreet==''){
		   jQuery('#txtStreet'+id+'_error').show();
	   }else{
		   jQuery('#txtStreet'+id+'_error').hide();
	   }

	   var txtStreet2 = jQuery('#txtStreet2'+id).val();
	   if(txtStreet2==''){
		   jQuery('#txtStreet2'+id+'_error').show();
	   }else{
		   jQuery('#txtStreet2'+id+'_error').hide();
	   }

	   var txtCity = jQuery('#txtCity'+id).val();
	   if(txtCity==''){
		   jQuery('#txtCity'+id+'_error').show();
	   }else{
		   jQuery('#txtCity'+id+'_error').hide();
	   }

	   var state = jQuery('#state'+id).val();
	   if(state==''){
		   jQuery('#state'+id+'_error').show();
	   }else{
		   jQuery('#state'+id+'_error').hide();
	   }

	   var txtZipCode = jQuery('#txtZipCode'+id).val();
	   if(txtZipCode==''){
		   jQuery('#txtZipCode'+id+'_error').show();
	   }else{
		   jQuery('#txtZipCode'+id+'_error').hide();
	   }

	   var txtPhoneArea = jQuery('#txtPhoneArea'+id).val()+"-"+jQuery('#txtPhonePrefix'+id).val()+"-"+jQuery('#txtPhoneSuffix'+id).val();
	   if(txtPhoneArea==''){
		   jQuery('#txtPhoneArea'+id+'_error').show();
	   }else{
		   jQuery('#txtPhoneArea'+id+'_error').hide();
	   }


	   var txtEmail = jQuery('#txtEmail'+id).val();
	   if(txtEmail==''){
		   jQuery('#txtEmail'+id+'_error').show();
	   }else{
		   jQuery('#txtEmail'+id+'_error').hide();
	   }
	   
	   var contactContent = jQuery('#contact_content'+id).val();

	    var form_data ={
				txtOrderNumber:txtOrderNumber,
				txtFname:txtFname,
				txtLname:txtLname,
				txtStreet:txtStreet,
				txtStreet2:txtStreet2,
				txtCity:txtCity,
				state:state,
				txtZipCode:txtZipCode,
				txtPhoneArea:txtPhoneArea,
				txtEmail:txtEmail,
				contactContent:contactContent
		   }
	   
	  
	   jQuery.ajax({
			url:"http://localhost/zippo-beta/index.php/OnlineOrder/Email",
		   data:form_data,
		   type:'POST',
		   dataType:'json',
		   success: function(msg){
			   
			   
			   }
		   
		   });
	   
	   
	   }
   </script>
    
  </div>
</div>

