<script>
$(document).ready(function(){

  $('.slider4').bxSlider({
   // slideWidth: 562,
    minSlides: 1,
    maxSlides: 1,
    moveSlides: 1,
    slideMargin: 0
  });
 
//$(".login-row").show() 

});

</script>
   
    <a href="#" id="prevslide" class="prevslide" title="previous slide"></a>
    <a href="#" id="nextslide" class="nextslide" title="next slide"></a>

<div id="main" class="clearfix" role="main">
  
  <section class="homeKickers row clearfix"> 
    <!-- eo .sect2of4black -->
    <section class="sect1of4black homeKicker clearfix">
      <div class="sect1of4blackBtm homeKickerBtm">
        <div class="innerKicker clearfix">
          <h3 class="txtBebas"> <img src="<?php echo $this->getSkinUrl('img/arw_right_red_5x9.png', array('_secure'=>true)) ?>" alt="" width="5" height ="9" style="position: relative; top: -4px;" /> LIGHTERS</h3>
          <img src="<?php echo $this->getSkinUrl('img/2ykopfjc.png', array('_secure'=>true)) ?>" alt="" class="homeKickerImg homeKickerImg2" />
          <p class="homeKickerP"> Whether looking for the perfect fragrance or that special accessory for your lighter, Zippo has it all. Shop Zippo's... </p>
        </div>
        <!-- eo .innerKicker --> 
        <br class="clear" />
        <span class="pillLinkLeft kickerLink home1of4Link clearfix"><a href="#">Shop Writing</a></span> </div>
      <!-- eo .sect1of4blackBtm --> 
    </section>
    <section class="sect1of4black homeKicker clearfix">
      <div class="sect1of4blackBtm homeKickerBtm">
        <div class="innerKicker clearfix">
          <h3 class="txtBebas"> <img src="<?php echo $this->getSkinUrl('img/arw_right_red_5x9.png', array('_secure'=>true)) ?>" alt="" width="5" height ="9" style="position: relative; top: -4px;" /> Accessories</h3>
          <img src="<?php echo $this->getSkinUrl('img/cvqzghrq.png', array('_secure'=>true)) ?>" alt="" class="homeKickerImg homeKickerImg2" />
          <p class="homeKickerP"> Whether looking for the perfect fragrance or that special accessory for your lighter, Zippo has it all. Shop Zippo's... </p>
        </div>
        <!-- eo .innerKicker --> 
        <br class="clear" />
        <span class="pillLinkLeft kickerLink home1of4Link clearfix"><a href="#">Shop Writing</a></span> </div>
      <!-- eo .sect1of4blackBtm --> 
    </section>
    <!-- eo .sect1of4black -->
    <section class="sect1of4black">
      <div class="sect1of4blackBtm homeKickerBtm">
        <div class="innerKicker clearfix">
          <h3 class="txtBebas"> <img src="<?php echo $this->getSkinUrl('img/arw_right_red_5x9.png', array('_secure'=>true)) ?>" alt="" width="5" height ="9" style="position: relative; top: -4px;" /> zippo outdoor </h3>
          <img src="<?php echo $this->getSkinUrl('img/home_kicker_3.png', array('_secure'=>true)) ?>" alt="" width="71" height="200" class="homeKickerImg" />
          <p class="homeKickerP skinnyP"> When you're in the wild you need gear you can count on. Rugged enough for any condition so you can enjoy the outdoors any time of year. </p>
        </div>
        <!-- eo .innerKicker --> 
        <span class="pillLinkLeft kickerLink home1of4Link clearfix"><a href="#">Shop Outdoor</a></span> </div>
      <!-- eo .sect1of4blackBtm --> 
    </section>
    <!-- eo .sect1of4black --> 
  </section>
  <!-- eo .homeKickers --> 
</div>
