<script>
jQuery(document).ready(function(){

 jQuery('.slider4').bxSlider({
   // slideWidth: 562,
    minSlides: 1,
    maxSlides: 1,
    moveSlides: 1,
    slideMargin: 0
  });
 
//$(".login-row").show() 

});

</script>
   
<div id="homeSlides">
<ul  class="homeSlides slider4">
    	<li class="homeSlide" style="background: #140f0b url('<?php echo $this->getSkinUrl('img/home_slide_1.png', array('_secure'=>true)) ?>') no-repeat center center;">
        
        <section class="homeCallout homeCallouts">

        <h3 class="txtViper" style="color:#85ad78;">Where<span class="txtRed" style="color:#000;">You</span>Go</h3>
        <p style="color:#85ad78;"> In the outdoors, getting a fire started quickly can be a matter of life and death. And with our Emergency Fire Starter Kit, starting
          a fire has never been easier. </p><br />

        <div class="callLink homeCallouts"> <span> <a href="#">Get the Grill</a> </span> </div>
      </section>
        
        </li>
    	<li class="homeSlide" style="background: #140f0b url('<?php echo $this->getSkinUrl('img/home_slide_2.jpg', array('_secure'=>true)) ?>') no-repeat center center;">
        
        <section class="homeCallout homeCallouts">
        <h3 class="txtViper"><span class="txtRed">Case</span>Knives</h3>
        <p> In the outdoors, getting a fire started quickly can be a matter of life and death. And with our Emergency Fire Starter Kit, starting
          a fire has never been easier. </p><br />

        <div class="callLink clearfix"> <span> <a href="#">Browse Knives</a> </span> </div>
      </section>
        
        </li>
    	<li class="homeSlide" style="background: #140f0b url('<?php echo $this->getSkinUrl('img/home_slide_3.png', array('_secure'=>true)) ?>') no-repeat center center;">
        
        <section class="homeCallout homeCallouts">
        <h3 class="txtViper" style="color:#00aeef">THE<span class="txtRed" style="color:#FFF;">Only</span>BLU</h3>
        <p> In the outdoors, getting a fire started quickly can be a matter of life and death. And with our Emergency Fire Starter Kit, starting
          a fire has never been easier. </p><br />

        <div class="callLink clearfix"> <span> <a href="#">Shop BLU®</a> </span> </div>
      </section>
        
        </li>
    	    
    </ul>
 </div>