<link  rel="stylesheet" href="<?php echo $this->getSkinUrl('css/jquery.jscrollpane.css', array('_secure' => true)) ?>">

        <script src="<?php echo $this->getSkinUrl('js/jquery.mousewheel.js', array('_secure' => true)) ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/jquery.jscrollpane.min.js', array('_secure' => true)) ?>"></script>
<!-- latest jQuery direct from google's CDN -->


		<script type="text/javascript" id="sourcecode">
			jQuery(function()
			{
				jQuery('.scroll-pane-before').jScrollPane(
					{
						showArrows: true,
						verticalArrowPositions: 'before',
						horizontalArrowPositions: 'before'
					}
				);
				jQuery('.scroll-pane-after').jScrollPane(
					{
						showArrows: true,
						verticalArrowPositions: 'after',
						horizontalArrowPositions: 'after'
					}
				);
				jQuery('.scroll-pane-os').jScrollPane(
					{
						showArrows: true,
						verticalArrowPositions: 'os',
						horizontalArrowPositions: 'os'
					}
				);
				jQuery('.scroll-pane-split').jScrollPane(
					{
						showArrows: true,
						verticalArrowPositions: 'split',
						horizontalArrowPositions: 'split'
					}
				);
			});
		</script>

<style type="text/css" id="page-css">
			/* Styles specific to this particular page */
			.scroll-pane-before,
			.scroll-pane-after,
			.scroll-pane-split,
			.scroll-pane-os
			{
				width: 90%;
			
				overflow: auto;
			}
			.horizontal-only
			{
				height: auto;
				
			}
			.jspTrack{
				width:576px !important;
				overflow:hidden;
			}
		</style>
<section class="row zOutdoor" >
  <section class="listHolder listHolderWhiteBg clearfix">
    <div class="listTop listOutdoors clearfix">
      <div class="listHero listOutdoorHero">
        <h3 class="listCatHead txtWhite txtBebas"> OUTDOORS </h3>
        <h5 class="listSubHead txtRed txtBebas"> Now Campfires Have an On Switch </h5>
        <p class="txtWhite"> Be ready for tailgating season with Zippo Outdoor products and accessories.
          A trustworthy companion through everyday life and uncommon adventures. </p>
      </div>
      <!-- eo .listHero --> 
    </div>
    <!-- eo .listTop -->
    
    <div class="listSlider">
    <div class="slideHdr clearfix">
                        	<h3 class="txtBebas">FIRE</h3><span class="listCount txtBebas">9 items</span>
                        </div>
    <div class="multiSlide">
    
    <div class="scroll-pane-os horizontal-only"  style="width:624px; height:250px;">
      <ul class="prodListSm clearfix   listPageProds" style="width: 1008px;">
                                        <li itemtype="http://schema.org/Product" itemscope=""><a itemprop="url" class="prodLink" title="Rugged Lantern™" href="http://www.zippo.com/product.aspx?id=1025704&amp;cid=1240"><img width="94" itemprop="image" alt="Rugged Lantern™" src="http://images.zippo.com/images/products/1_1025704_TH.JPG"><span class="newTag"></span></a>
                            <span itemtype="http://schema.org/Offer" itemscope="" itemprop="offers" class="prodListPrice"><span itemprop="price">$89.95</span></span>
                        </li><li itemtype="http://schema.org/Product" itemscope=""><a itemprop="url" class="prodLink" title="Harley-Davidson® Hand Warmer" href="http://www.zippo.com/product.aspx?id=1027153&amp;cid=1240"><img width="94" itemprop="image" alt="Harley-Davidson® Hand Warmer" src="http://images.zippo.com/images/products/1_1027153_TH.JPG"><span class="newTag"></span></a>
                            <span itemtype="http://schema.org/Offer" itemscope="" itemprop="offers" class="prodListPrice"><span itemprop="price">$29.95</span></span>
                        </li><li itemtype="http://schema.org/Product" itemscope=""><a itemprop="url" class="prodLink" title="Hand Warmer" href="http://www.zippo.com/product.aspx?id=1025744&amp;cid=1240"><span class="btnCustomize"></span><img width="94" itemprop="image" alt="Hand Warmer" src="http://images.zippo.com/images/products/1_1025744_TH.JPG"></a>
                            <span itemtype="http://schema.org/Offer" itemscope="" itemprop="offers" class="prodListPrice"><span itemprop="price">$19.95</span></span>
                        </li><li itemtype="http://schema.org/Product" itemscope=""><a itemprop="url" class="prodLink" title="Realtree Hand Warmer" href="http://www.zippo.com/product.aspx?id=1025291&amp;cid=1240"><img width="94" itemprop="image" alt="Realtree Hand Warmer" src="http://images.zippo.com/images/products/1_1025291_TH.JPG"></a>
                            <span itemtype="http://schema.org/Offer" itemscope="" itemprop="offers" class="prodListPrice"><span itemprop="price">$29.95</span></span>
                        </li><li itemtype="http://schema.org/Product" itemscope=""><a itemprop="url" class="prodLink" title="Black Hand Warmer" href="http://www.zippo.com/product.aspx?id=1025148&amp;cid=1240"><img width="94" itemprop="image" alt="Black Hand Warmer" src="http://images.zippo.com/images/products/1_1025148_TH.JPG"></a>
                            <span itemtype="http://schema.org/Offer" itemscope="" itemprop="offers" class="prodListPrice"><span itemprop="price">$19.95</span></span>
                        </li><li itemtype="http://schema.org/Product" itemscope=""><a itemprop="url" class="prodLink" title="Fuel Canister" href="http://www.zippo.com/product.aspx?id=1024754&amp;cid=1240"><img width="94" itemprop="image" alt="Fuel Canister" src="http://images.zippo.com/images/products/1_1024754_TH.JPG"></a>
                            <span itemtype="http://schema.org/Offer" itemscope="" itemprop="offers" class="prodListPrice"><span itemprop="price">$14.95</span></span>
                        </li><li itemtype="http://schema.org/Product" itemscope=""><a itemprop="url" class="prodLink" title="Heat Gift Set" href="http://www.zippo.com/product.aspx?id=1025960&amp;cid=1240"><img width="94" itemprop="image" alt="Heat Gift Set" src="http://images.zippo.com/images/products/1_1025960_TH.JPG"></a>
                            <span itemtype="http://schema.org/Offer" itemscope="" itemprop="offers" class="prodListPrice"><span itemprop="price">$39.95</span></span>
                        </li><li itemtype="http://schema.org/Product" itemscope=""><a itemprop="url" class="prodLink" title="Hand Warmer Replacement Burner" href="http://www.zippo.com/product.aspx?id=1024742&amp;cid=1240"><img width="94" itemprop="image" alt="Hand Warmer Replacement Burner" src="http://images.zippo.com/images/products/1_1024742_TH.JPG"></a>
                            <span itemtype="http://schema.org/Offer" itemscope="" itemprop="offers" class="prodListPrice"><span itemprop="price">$7.95</span></span>
                        </li></ul>
    </div>
    
    
    
    </div>
    </div>
    
    <!-- eo .listSlider --> 
  </section>
  <!-- eo .listHolder -->
  <section class="listKickersRight">
                	<section class="listKickerAdTop">
                    	
                    </section><!-- eo .listKickerAdTop -->
                	<section class="bestSellKicker" style="margin-top:0;">
                    	<div class="inner clearfix">
                        	<h3 class="bestSellHdr txtBebas">
                            	best sellers
                            </h3>
                            <div class="bsSlider">
                            	<div class="bsFaker"></div>
                            	<strong class="shortDesc"></strong>
                            	<div class="bsSlideWrap clearfix" id="bsKickSlide">
                                    <ul id="bestSellersList">
                                    	<li class="bsSlideItem"><img src="<?php echo $this->getSkinUrl('img/bsSlider1.jpg', array('_secure'=>true)) ?>" alt="First rugged yet refined classic" /></li>
                                    	<li class="bsSlideItem"><img src="<?php echo $this->getSkinUrl('img/bsSlider1.jpg', array('_secure'=>true)) ?>" alt="2nd rugged yet refined classic" /></li>
                                    	<li class="bsSlideItem"><img src="<?php echo $this->getSkinUrl('img/bsSlider1.jpg', array('_secure'=>true)) ?>" alt="3rd rugged yet refined classic" /></li>
                                    </ul>
                                	<!--<div class="bsSlideItem onDeck prevItem"><img src="assets/img/bsSlider1.jpg" alt="product name" width="107" height="146" /></div>-->
                                	<!--<div class="bsSlideItem onDeck nextItem"><img src="assets/img/bsSlider1.jpg" alt="product name" width="107" height="146" /></div>-->
                                </div>
                            </div>
                            <div class="sliderLinks clearfix">
                            	<a id="btnBsProdInfo" href="ProductDetail.html" title="product info"></a>
                            	<a id="btnBsAddCart" href="#" title="add to cart"></a>
                            </div>
                        </div>
                    </section><!-- eo .listKickerSlide -->
                    <!-- eo .kickerPromo -->
                </section>
  <!-- eo .listKickersRight --> 
</section>
