<?php
$visibility = array(
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
);
$storeId = Mage::app()->getStore()->getId();
$products = Mage::getResourceModel('reports/product_collection')
                ->addOrderedQty()
                ->addAttributeToFilter('visibility', $visibility)
                ->addAttributeToSelect('*')
                ->setStoreId($storeId)
                ->addStoreFilter($storeId)
                ->setOrder('ordered_qty', 'desc')
                ->getSelect()->limit(10)->query();
?>
<?php
$visibility = array(
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
);
$storeId = Mage::app()->getStore()->getId();
$products = Mage::getResourceModel('reports/product_collection')
                ->addOrderedQty()
                ->addAttributeToFilter('visibility', $visibility)
                ->addAttributeToSelect('*')
                ->setStoreId($storeId)
                ->addStoreFilter($storeId)
                ->setOrder('ordered_qty', 'desc')
                ->getSelect()->limit(10)->query();
if (count($products) > 0):
?>


    <section class="bestSellKicker" style="margin-top:0;">
        <div class="inner clearfix">
            <h3 class="bestSellHdr txtBebas">
                best sellers
            </h3>
            <div class="bsSlider">
                <div class="bsFaker"></div>
                <strong class="shortDesc"></strong>
                <div class="bsSlideWrap clearfix" id="bsKickSlide">
                    <ul id="bestSellersList">
                        <?php foreach ($products as $_product):?>
                        <?php $product = Mage::getModel('catalog/product');
						$product->load($_product['entity_id']);?>
                         <li class="bsSlideItem"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(100)?>" alt="<?php echo $product->getName()?>" /></li>
                        
                             <?php endforeach;?>
                    </ul>
                    <div class="sliderLinks clearfix">
                <a id="btnBsProdInfo" href="<?php echo $product->getProductUrl()?>" title="product info"></a>
                <a id="btnBsAddCart" href="#" onclick="setLocation('<?php echo Mage::getUrl('checkout/cart/add/product/'.$product->getId())?>')"title="add to cart"></a>
            </div>
                </div>
            </div>            
        </div>
    </section>

<?php endif;