<script>
function test (){
	jQuery(".pouplist li .btnAddCart").click(function(e) {
		jQuery(".productListingPopup .prodCart").stop();
		jQuery(".productListingPopup .prodCart").append("<span class='loader-cart'></span>");
		setTimeout(function(){
			jQuery(".productListingPopup .prodCart span").remove();
			jQuery(".productListingPopup .inner").append("<div class='addedincart'>successfully added to your cart</div>");
			jQuery("html").clearQueue();
			jQuery(".productListingPopup .prodCart").clearQueue();
			//jQuery("html").animate({scrollTop: 0}, 500);
			
			return false;
		 
		 }, 4000);
		
		setTimeout(function(){
		jQuery(".pouplist li .listProdPopUps").hide();
		jQuery(".productListingPopup .addedincart").remove();
		return false;
		}, 6000);

    });



	
}

jQuery(document).ready(function(e) {
  test(); 
});

</script>

<script>
(function($) {
    $.event.special.mousestop = {
        setup: function(data) {
            $(this).data('mousestop', _data(data))
                   .bind('mouseenter.mousestop', _mouseenter)
                   .bind('mouseleave.mousestop', _mouseleave)
                   .bind('mousemove.mousestop', _mousemove);
        },
        teardown: function() {
            $(this).removeData('mousestop')
                   .unbind('.mousestop');
        }
    };

    function _mouseenter() {
        var _self = this,
            data = $(this).data('mousestop');

        this.movement = true;

        if(data.timeToStop) {
            this.timeToStopTimer = window.setTimeout(function() {
                _self.movement = false;
                window.clearTimeout(_self.timer);
            }, data.timeToStop);
        }
    }

    function _mouseleave() {
        window.clearTimeout(this.timer);
        window.clearTimeout(this.timeToStopTimer);
    }
    
    function _mousemove() {
        var $el = $(this),
            data = $el.data('mousestop');

        if(this.movement) {
            window.clearTimeout(this.timer);
            this.timer = window.setTimeout(function() {
                $el.trigger('mousestop');
            }, data.delay);
        }
    }

    function _data(data) {
        if($.isNumeric(data)) {
            data = {delay: data};
        }
        else if(typeof data !== 'object') {
            data = {};
        }

        return $.extend({}, $.fn.mousestop.defaults, data);
    }

    $.fn.mousestop = function(data, fn) {
        if (typeof data === 'function') { fn = data; }
        return arguments.length > 0 ? this.bind('mousestop', data, fn) : this.trigger('mousestop');
    };

    $.fn.mousestop.defaults = {
        delay: 300,
        timeToStop: null
    };
})(jQuery);



jQuery(document).ready(function(e) {
	getScreen = jQuery(window).width();
	
	var getlast = getScreen * 54 / 100 ;
	
	jQuery(".multiSlide .prodListSm li").mousestop(300, function() {
		
		jQuery(".pouplist li").children(".listProdPopUps").clearQueue();
		jQuery(".pouplist li").children(".listProdPopUps").hide();
		jQuery(".pouplist li").children(".listProdPopUps").removeClass("activePopupNew");
		jQuery(eTop).stop();
		var eTop = jQuery(this).offset().top; //get the offset top of the element
		console.log(eTop - jQuery(window).scrollTop());
		var eTopFinal = eTop - jQuery(window).scrollTop();
		jQuery(eTopFinal).clearQueue();
		
		jQuery(".pouplist li .listProdPopUps").hide();
		var getID = jQuery(this).data("id")-1;

		var getdelay = jQuery(".pouplist li").eq(getID).children(".listProdPopUps").fadeIn(300).addClass("activePopupNew");
		
		var position = jQuery(this).offset();
		jQuery(".pouplist li").eq(getID).children(".listProdPopUps").css( "left", position.left );
		jQuery(".pouplist li").eq(getID).children(".listProdPopUps").css( "top", eTopFinal );

		if(position.left > getlast){
		  jQuery(".pouplist li").eq(getID).addClass("reverse");
	    }
	
	});

	
	jQuery(".multiSlide .prodListSm li").mouseover(function(e) {});

	jQuery(".multiSlide").mouseleave(function(e) {
         jQuery(".pouplist li .listProdPopUps").hide();
		 jQuery(".pouplist li").removeClass("reverse");
    });

	jQuery(".productListingPopup").mouseleave(function(e) {
        jQuery(".pouplist li .listProdPopUps").hide();
		 jQuery(".pouplist li").removeClass("reverse");
    });
	
});

</script>
<style type="text/css" id="page-css">
/* Styles specific to this particular page */


.scroll-pane-before, 
.scroll-pane-after, 
.scroll-pane-split, 
.scroll-pane-os {
	width: 90%;
	overflow: auto;
}
.horizontal-only {
	height: auto;
}
.jspTrack {
	width: 576px !important;
	overflow: hidden;
}
.listProdPopUps{
	position:fixed !important;
	margin-left:80px !important;
	margin-top:-250px !important;
}
</style>
<?php
$catModel = Mage::getModel('catalog/category');
$prodModel = Mage::getModel('catalog/product');
$_helper = $this->helper('catalog/output');
$categoryId = $this->getCategoryId();
$mainCategory = $catModel->load($categoryId);
$childern = $mainCategory->getChildren();
?>
<section class="row zOutdoor" >
  <section class="listHolder listHolderWhiteBg clearfix">
    <div class="listTop listOutdoors clearfix" <?php if ($mainCategory->getImageUrl()): ?> style="background:url('<?php echo $mainCategory->getImageUrl() ?> <?php endif; ?>')">
      <div class="listHero listOutdoorHero">
        <h3 class="listCatHead txtWhite txtBebas"> <?php echo $mainCategory->getName(); ?> </h3>
        <?php echo $mainCategory->getDescription(); ?> </div>
    </div>
    <div class="listSlider">
      <?php foreach (explode(',',$childern) as $subCatid): ?>
      <?php
                $child = Mage::getModel('catalog/category')->load($subCatid);  
                $collection = $prodModel->getCollection()
                        ->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left')
                        ->addAttributeToSelect('*')
                        ->addUrlRewrite($child->getId())
                        ->addAttributeToFilter('category_id', array('eq' => $child->getId()));
                ?>
      <?php $_collectionSize = $collection->count() ?>
      <div class="slideHdr clearfix">
        <h3 class="txtBebas"><?php echo $child->getName() ?></h3>
        <span class="listCount txtBebas"><?php echo $_collectionSize; ?>&nbsp;<?php echo $this->__('items') ?> </span> </div>
      <div class="multiSlide">
        <div class="scroll-pane-os horizontal-only"  style="width:624px; height:250px;">
          <ul class="prodListSm clearfix   listPageProds" style="width: <?php echo $_collectionSize * 126 ?>px;">
            <?php foreach ($collection as $product): ?>
           <?php $i ++ ?>
            <li data-id="<?php echo $i?>"><a class="prodLink" title="<?php echo $product->getName() ?>" href="<?php echo $product->getProductUrl() ?>"><img width="94" alt="<?php echo $product->getName() ?>" src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(200) ?>">
              <?php if (Mage::helper('zippo')->isNew($product)): ?>
              <span class="newTag"></span>
              <?php endif; ?>
              </a>
              <span class="prodListPrice"><?php echo $this->getPriceHtml($product, true) ?></span>
              <div class="listProdPopUps">
                <div class="productListingPopup clearfix">
                  <div class="inner clearfix">
                    <div class="prodHero"><img id="product-collection-image-<?php echo $product->getId(); ?>"
                                                                           src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(162, 230); ?>"
                                                                           alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" /></div>
                    <div class="popRight">
                      <h2 class="jProductName txtRed"><?php echo $_helper->productAttribute($product, $product->getName(), 'name') ?></h2>
                      <h3 class="jProductPrice"><?php echo $this->getPriceHtml($product, true) ?>
                        <?php if ($product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($product, 'short') ?>
                        <?php endif; ?>
                      </h3>
                      <h3 class="jProductSKU"> <?php echo nl2br($product->getSku()) ?> <?php echo $this->getChildHtml('product_type_availability'); ?> </h3>
                      <div class="jProductDescription prodLongDesc"> <?php echo $_helper->productAttribute($product, nl2br($product->getShortDescription()), 'short_description') ?> </div>
                      <img src="<?php echo $this->getSkinUrl('img/prod_made_USA.gif', array('_secure' => true)) ?>" alt="Made in the USA" width="125" height="30">
                      <div class="prodCart">
                        <label for="txtProdQty"><?php echo $this->__('Qty.') ?></label>
                        <input type="text" name="txtProdQty" id="txtProdQty" class="txtProdQty" placeholder="1" size="1">
                        <input type="button" class="btnAddCart" onclick="setLocation('<?php echo $this->getAddToCartUrl($product) ?>')" value="<?php echo $this->__('Add To Cart')?>">
                      </div>
                    </div>
                  </div>
                  <!-- eo .inner --> 
                  <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->stripTags($product->getName(), null, true) ?>" class="btnProdClickreviews"><?php echo $this->__('Click for more info!')?></a> </div>
              </div>
            </li>
            <?php endforeach ?>
          </ul>
          
        </div>
        <ul class="pouplist">
           <?php foreach ($collection as $product): ?>
            <li>
              <div class="listProdPopUps">
                <div class="productListingPopup clearfix">
                  <div class="inner clearfix">
                    <div class="prodHero"><img id="product-collection-image-<?php echo $product->getId(); ?>"
                                                                           src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(162, 230); ?>"
                                                                           alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" /></div>
                    <div class="popRight">
                      <h2 class="jProductName txtRed"><?php echo $_helper->productAttribute($product, $product->getName(), 'name') ?></h2>
                      <h3 class="jProductPrice"><?php echo $this->getPriceHtml($product, true) ?>
                        <?php if ($product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($product, 'short') ?>
                        <?php endif; ?>
                      </h3>
                      <h3 class="jProductSKU"> <?php echo nl2br($product->getSku()) ?> <?php echo $this->getChildHtml('product_type_availability'); ?> </h3>
                      <div class="jProductDescription prodLongDesc"> <?php echo $_helper->productAttribute($product, nl2br($product->getShortDescription()), 'short_description') ?> </div>
                      <img src="<?php echo $this->getSkinUrl('img/prod_made_USA.gif', array('_secure' => true)) ?>" alt="Made in the USA" width="125" height="30">
                      <div class="prodCart">
                        <label for="txtProdQty"><?php echo $this->__('Qty.') ?></label>
                        <input type="text" name="txtProdQty" id="txtProdQty" class="txtProdQty" placeholder="1" size="1">
                        <input type="button" class="btnAddCart" onclick="setLocation('<?php echo $this->getAddToCartUrl($product) ?>')" value="<?php echo $this->__('Add To Cart')?>">
                      </div>
                    </div>
                  </div>
                  <!-- eo .inner --> 
                  <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->stripTags($product->getName(), null, true) ?>" class="btnProdClickreviews"><?php echo $this->__('Click for more info!')?></a> </div>
              </div>
            </li>
            <?php endforeach ?>
          </ul>
      </div>
      <?php endforeach; ?>
    </div>
  </section>
  <section class="listKickersRight"> <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('bestseller')->toHtml(); ?> </section>
</section>


