<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>

<style>
    html, body {
        height: auto ;
    }
</style>
<?php
$cmspages = $this->getCmsCollection();
?>
<div class="search-cout">Your search returned <?php echo count($cmspages) ?> results</div>
<?php if (count($cmspages)): ?>
    <div class="cmsResult">
        <?php foreach ($cmspages as $_page): ?>
            <div class="cmsResult-itmes prodListRow">
                <a href="<?php echo $this->getUrl($_page['identifier']) ?>" title="<?php echo $_page['title'] ?>" >
                    <?php echo getHTMLByID($_page['content']);?>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
</div>
<?php

function getHTMLByID($html) {
    $doc = new DOMDocument();
    libxml_use_internal_errors(true);
    $doc->loadHtml($html); // $some_html should contain your html string  
    $xpath = new DOMXPath($doc);
    $result = $xpath->query('//*[@id="searchListText"]');
    if (!empty($result)) {
        foreach ($result as $link) {
            return substr($link->nodeValue, 0, 300);
        }
    }
    return FALSE;
}
?>
<script>
    $j(document).ready(function() {

        /* Every time the window is scrolled ... */
        $j(window).scroll(function() {
            $j('li.search-cms').each(function() {
                var bottom_of_object = $j(this).position().top + $j(this).outerHeight();
                var bottom_of_window = $j(window).scrollTop() + $j(window).height();

                /* If the object is completely visible in the window, fade it it */
                if (bottom_of_window > bottom_of_object) {
                    $j('#search-loader').show();
                    $j(this).animate({'opacity': '1'}, 300);
                    setTimeout(function() {
                        $j('#search-loader').hide();
                        return false;
                    }, 400);
                } else {
                    $j(this).animate({'opacity': '0'}, 300);
                }
            });
        });
    });
</script>
