<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>

<style>
    html, body {
        height: auto ;
    }
</style>
<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$obj  = new Mage_Catalog_Block_Product_List();
?>
<?php if (!$_productCollection->count()): ?>
    <section id="searchProducts" class="searchProducts clearfix">
        <div class="listProdHolder clearfix"><p class="note-msg" style="text-align: center; padding-top:20px;"><?php echo $this->__('There are no products matching the selection.') ?></p></div>
    </section>

<?php else: ?>
    <div class="category-products">           
                            <?php $this->setData('column_count', 4); // Grid Mode  ?>

                            <?php $_collectionSize = $_productCollection->count() ?>
                            <?php $_columnCount = 4;?>
                            <?php
                            $i = 0;
                            foreach ($_productCollection as $_product):
                                if (!($_product->isSaleable())){continue;}
                                ?>
                                <?php if ($i++ % $_columnCount == 0): ?>
                                    <ul class="products-grid listLighters  products-grid--max-<?php echo $_columnCount; ?>-col">
                                    <?php endif ?>
                                    <li class="<?php if (($i - 1) % $_columnCount == 0): ?> first <?php elseif ($i + -2): ?> reverse <?php elseif ($i % $_columnCount == 0): ?> reverse<?php endif; ?> ">
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName() ?>" class="prodLink">
                                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(162, 230); ?>"
                                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                        </a>
                                        <p><?php echo $_product->getName() ?></p>
                                        <p><?php echo $_product->getSku() ?></p>                                          
                                        <?php echo Mage::helper('core')->currency($_product->getPrice()); ?>
                                    </li>
                                <?php endforeach ?>
                            </ul>
                            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script> 
                        </div>
<?php endif; ?>
