<script type="text/javascript" id="sourcecode">
			jQuery(function()
			{
				jQuery('.scroll-pane-before').jScrollPane(
					{
						showArrows: true,
						verticalArrowPositions: 'before',
						horizontalArrowPositions: 'before'
					}
				);
				jQuery('.scroll-pane-after').jScrollPane(
					{
						showArrows: true,
						verticalArrowPositions: 'after',
						horizontalArrowPositions: 'after'
					}
				);
				jQuery('.scroll-pane-os').jScrollPane(
					{
						showArrows: true,
						verticalArrowPositions: 'os',
						horizontalArrowPositions: 'os'
					}
				);
				jQuery('.scroll-pane-split').jScrollPane(
					{
						showArrows: true,
						verticalArrowPositions: 'split',
						horizontalArrowPositions: 'split'
					}
				);
			});
		</script>

<style type="text/css" id="page-css">
			/* Styles specific to this particular page */
			.scroll-pane-before,
			.scroll-pane-after,
			.scroll-pane-split,
			.scroll-pane-os
			{
				width: 90%;
			
				overflow: auto;
			}
			.horizontal-only
			{
				height: auto;
				
			}
			.jspTrack{
				width:576px !important;
				overflow:hidden;
			}
		</style>
<?php
$catModel = Mage::getModel('catalog/category');
$prodModel = Mage::getModel('catalog/product');
$categoryId = $this->getCategoryId();
$childern = $catModel->load($categoryId)->getChildrenCategories();
?>
<section class="row zOutdoor" >
  <section class="listHolder listHolderWhiteBg clearfix">
    <div class="listTop listOutdoors clearfix">
      <div class="listHero listOutdoorHero">
        <h3 class="listCatHead txtWhite txtBebas"> OUTDOORS </h3>
        <h5 class="listSubHead txtRed txtBebas"> Now Campfires Have an On Switch </h5>
        <p class="txtWhite"> Be ready for tailgating season with Zippo Outdoor products and accessories.
          A trustworthy companion through everyday life and uncommon adventures. </p>
      </div>
      <!-- eo .listHero --> 
    </div>
<?php foreach ($childern as $child): ?>
    <?php
    $collection = $prodModel->getCollection()
            ->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left')
            ->addAttributeToSelect('*')
            ->addAttributeToFilter('category_id', array('eq' => $child->getId()));
    ?>
    <?php $_collectionSize = $collection->count() ?>
    <div class="listSlider">
        <div class="slideHdr clearfix">
            <h3 class="txtBebas"><?php $child->getName() ?></h3><span class="listCount txtBebas"><?php echo $_collectionSize; ?>&nbsp;<?php echo $this->__('items') ?> </span>
        </div>
        <div class="multiSlide">
            <div class="scroll-pane-os horizontal-only"  style="width:624px; height:250px;">
                <ul class="prodListSm clearfix   listPageProds" style="width: 1008px;">
                    <?php foreach ($collection as $product): ?>
                       <li><a class="prodLink" title="<?php echo $product->getName()?>" href="<?php echo $product->getUrl()?>"><img width="94" alt="Rugged Lanternâ„¢" src="http://images.zippo.com/images/products/1_1025704_TH.JPG"><span class="newTag"></span></a>
                            <li><a class="prodLink" title="<?php echo $product->getName()?>" href="<?php echo $product->getUrl()?>"><img width="94" alt="Rugged Lanternâ„¢" src="http://images.zippo.com/images/products/1_1025704_TH.JPG"><span class="newTag"></span></a>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
    </div>
<?php endforeach;?>
      <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('bestseller')->toHtml();?> 
  </section>
</section>
