<?php
$catModel = Mage::getModel('catalog/category');
$prodModel = Mage::getModel('catalog/product');
$categoryId = $this->getCategoryId();
$mainCategory = $catModel->load($categoryId);
$childern = $catModel->load($categoryId)->getChildrenCategories();
?>
<section class="row zOutdoor" >
  <section class="listHolder listHolderWhiteBg clearfix">
      <div class="listTop listOutdoors clearfix" style="background:url(<?php echo $mainCategory->getImageUrl()?>)">
      <div class="listHero listOutdoorHero">
          <h3 class="listCatHead txtWhite txtBebas"> <?php echo $mainCategory->getData('name');?> </h3>        
        <?php echo $mainCategory->getData('description');?>
      </div>
      <!-- eo .listHero --> 
    </div>
<?php foreach ($childern as $child): ?>
    <?php
    $collection = $prodModel->getCollection()
            ->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left')
            ->addAttributeToSelect('*')
            ->addAttributeToFilter('category_id', array('eq' => $child->getId()));
    ?>
    <?php $_collectionSize = $collection->count() ?>
    <div class="listSlider">
        <div class="slideHdr clearfix">
            <h3 class="txtBebas"><?php echo $child->getName() ?></h3><span class="listCount txtBebas"><?php echo $_collectionSize; ?>&nbsp;<?php echo $this->__('items') ?> </span>
        </div>
        <div class="multiSlide">
            <div class="scroll-pane-os horizontal-only"  style="width:624px; height:250px;">
                <ul class="prodListSm clearfix   listPageProds" style="width: 11008px;">
                    <?php foreach ($collection as $product): ?>
                       <li><a class="prodLink" title="<?php echo $product->getName()?>" href="<?php echo $product->getProductUrl()?>"><img width="94" alt="Rugged Lanternâ„¢" src="http://images.zippo.com/images/products/1_1025704_TH.JPG"><span class="newTag"></span></a>
                   <?php endforeach ?>
                </ul>
            </div>
        </div>
    </div>
<?php endforeach;?>
      <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('bestseller')->toHtml();?> 
  </section>
</section>
