<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>

<style>
    html, body {
        height: auto ;
    }
</style>
<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$obj  = new Mage_Catalog_Block_Product_List();
?>
<?php if (!$_productCollection->count()): ?>
    <section id="searchProducts" class="searchProducts clearfix">
        <div class="listProdHolder clearfix"><p class="note-msg" style="text-align: center; padding-top:20px;"><?php echo $this->__('There are no products matching the selection.') ?></p></div>
    </section>

<?php else: ?>

    <div class="category-products">   
     <ul class="products-grid listLighters  products-grid--max-<?php echo $_columnCount; ?>-col">        
                            <?php $this->setData('column_count', 4); // Grid Mode  ?>

                            <?php $_collectionSize = $_productCollection->count() ?>
                            <?php $_columnCount = 4;?>
                            <?php
                            $i = 0;
                            foreach ($_productCollection as $_product):
                                if (!($_product->isSaleable())){continue;}
                                ?>
                                <?php if ($i++ % $_columnCount == 0): ?>
                                   
                                    <?php endif ?>
                                    <li class="<?php if (($i - 1) % $_columnCount == 0): ?> first <?php elseif ($i + -2): ?> reverse <?php elseif ($i % $_columnCount == 0): ?> reverse<?php endif; ?> ">
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName() ?>" class="prodLink">
                                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(162, 230); ?>"
                                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                            <?php if (Mage::helper('zippo')->isNew($_product)): ?>
                                                        <span class="newTag"></span>
                                                    <?php endif; ?>
                                        </a>
                                        <p><strong><?php echo $_product->getName() ?></strong></p>
                                        <p><?php echo $_product->getSku() ?></p>                                          
                                        <?php echo Mage::helper('core')->currency($_product->getPrice()); ?>
                                        
                                        <?php $block = new Mage_Catalog_Block_Product_List()?>
                                         <div class="listProdPopUps">
                                                <div class="productListingPopup clearfix">
                                                    <div class="inner clearfix">
                                                        <div class="prodHero"><img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                                                                   src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(162, 230); ?>"
                                                                                   alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></div>
                                                        <div class="popRight">
                                                            <h2 class="jProductName txtRed"><?php echo $_product->getName() ?></h2>
                                                            <h3 class="jProductPrice">
                                                                <?php echo $this->getPriceHtml($_product, true) ?>
                                                                <?php if ($_product->getRatingSummary()): ?>
                                                                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                                                <?php endif; ?></h3>


                                                            <h3 class="jProductSKU"> <?php echo nl2br($_product->getSku()) ?> <?php echo $this->getChildHtml('product_type_availability'); ?> </h3>
                                                            <div class="jProductDescription prodLongDesc">
                                                                <?php echo $_product->getShortDescription()?>
                                                            </div>
                                                            <?php if ($_product->getCountryOfManufacture() == 'US'): ?>
                                                                <img src="<?php echo $this->getSkinUrl('img/prod_made_USA.gif', array('_secure' => true)) ?>" alt="Made in the USA" width="125" height="30">
                                                            <?php endif; ?>                                                            
                                                            <div class="prodCart">
                                                                <label for="txtProdQty"><?php echo $this->__('Qty.') ?></label> <input type="text" name="txtProdQty" id="txtProdQty<?php echo $_product->getId() ?>" class="txtProdQty" placeholder="1" size="1">
                                                                <input type="button" class="btnAddCart" onclick="addtocart('<?php echo $_product->getId() ?>', '<?php echo $block->getAddToCartUrl($_product) ?>?options=cart')" value="Add To Cart">
                                                            </div>
                                                        </div>
                                                    </div><!-- eo .inner -->
                                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="btnProdClickreviews">Click for more info!</a>
                                                </div>           
                                            </div>
                                        
                                        
                                    </li>
                                    <?php if ($i % $_columnCount == 0): ?>
                                    </ul>
                                    <?php endif ?>
                                <?php endforeach ?>
                            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script> 
                        
<?php endif; ?>


</ul>
</div>
<div class="search-cout">

Your search returned <?php  echo $i  ?> results</div>
